services:
  postgres:
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  seed:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ugram-seed
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - ugram-net
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: sh -c "pnpm --dir backend run prisma:seed:deploy"
    restart: "no"

  backend:
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully
